### ISSUE TITLE
[QUESTION] Android build instructions

### ISSUE THREAD

**Issue by cookieguru** [metrodroid/metrodroid#859]
There have been [a lot of commits since the last release](https://github.com/metrodroid/metrodroid/compare/v3.0.0...master) and I'm eager to play with many of them.  So I created a simple GHA on my fork which is just a thin wrapper for running `./gradlew assembleRelease`.

<details>
<summary>Workflow</summary>

```yml
name: Build Android

on: workflow_dispatch

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: set up Java
        uses: actions/setup-java@v4
        with:
          cache: gradle
          distribution: 'temurin'
          java-version: 11
      - name: Make gradlew executable
        run: chmod +x ./gradlew
      - name: Build
        run: ./gradlew assembleRelease
      - name: Upload
        uses: actions/upload-artifact@v4
        with:
          compression-level: 0
          if-no-files-found: 'error'
          name: metrodroid-release-unsigned.apk.zip
          path: build/outputs/apk/release/metrodroid-release-unsigned.apk
```
</details>

I had to [rename a few variables](https://pastes.io/raw/msxffl7g5u) to get the app to compile.

When I try to install the built apk on a physical device, it fails:
```shell
$ adb install metrodroid-release-unsigned.apk 
Performing Streamed Install
adb: failed to install metrodroid-release-unsigned.apk: Failure [INSTALL_PARSE_FAILED_NO_CERTIFICATES: Failed collecting certificates for /data/app/vmdl1130013967.tmp/base.apk: Failed to collect certificates from /data/app/vmdl1130013967.tmp/base.apk: Attempt to get length of null array]
```

1. Is Java 11 the right version to use?
2. Is `assembleRelease` the right command to use?
3. Any ideas what's going on with the cert issue on install?
4. What command are others using to build/deploy this locally?
